/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/
#include<stdio.h>
#include <stdlib.h>
#define limit 4000000

int main()
{
    int fibo[40];
    int i, last_index = 2;
    long long sum = 0;
  
    fibo[0] = 0;
    fibo[1] = 1;
    for(last_index = 2; ;last_index++)
    {
        fibo[last_index] = fibo[last_index - 1] + fibo[last_index - 2];
      
        if(fibo[last_index] > limit)
        {
        	break;
        }
    }

    //Every third term in the Fibonacci series is even. So, we sum over it.
    for(i = 3; i < last_index;i = i+3)
    {
        sum = sum + fibo[i];
    }

    printf("%lld.\n",sum);

    return 0;
}
